# Solarized Dark Theme for Hebi
# Website:    https://ethanschoonover.com/solarized
# Repository: https://github.com/altercation/solarized
# Colors:     https://github.com/subtheme-dev/solarized/blob/master/colors/dark.yaml

# Solarized Dark Base 01
walls = "586e75"

# Solarized Dark Base 02
background = "073642"

# Solarized Dark Base 2
snake = "eee8d5"

food = [
    # Solarized Yellow
    "b58900",

    # Solarized Orange
    "cb4b16",

    # Solarized Red
    "dc322f",

    # Solarized Magenta
    "d33682",

    # Solarized Violet
    "6c71c4",

    # Solarized Blue
    "268bd2",

    # Solarized Cyan
    "2aa198",

    # Solarized Green
    "859900"
]